const SNAKE_ENTITY_HEAD = 0
const SNAKE_ENTITY_TAIL = 1
const SNAKE_ENTITY_FOOD = 2

const SNAKE_START_TPS          = 1.0
const SNAKE_TPS_INCREMENTATION = 0.1

const SNAKE_PLAYER_COLOR = new ESColor(0, 255, 0)
const SNAKE_FOOD_COLOR   = new ESColor(255, 0, 0)
